### ISSUE TITLE
Dynamically set current page title

### ISSUE THREAD

**Issue by JoshuaNovak919** [monbro/meteor-breadcrumb-plugin#2]
Is there a way to set the current page title dynamically if it isn't in the url? For example when editing a post page the url would be `posts/:_id/edit`. I'd like to be able to set the page title to the actual name of the post through the template helper or something, but still have the id in the url.

**Comment by monbro** [comment]
That should be possible by using a anonymous function for the title attribute.

For e.g. when you are using something like http://meteortips.com/tutorial/iron-router-part-2/ (scroll down) to get your post data - you should be able to use this data function as well. I will try to add a working example with that. But maybe it should look something like this (not tested):

```
Router.route('/post/:_id/edit', {
  name: 'editpost',
  template: 'singleBlogPostEdit',
  parent: 'home',
  title: function() {
      var blogPostName = this.data().name; // depends if your object in mongodb hast the attribute name or title anything else.
      return 'Edit Blog Post '+blogPostName;
  },
  data: function(){
      var blogPostId = this.params._id;
      return Posts.findOne({_id: blogPostId});
  }
});
```

**Comment by JoshuaNovak919** [comment]
I tried what you suggested, but now none of the breadcrumbs show up. If I call `title()` instead of `title` it seems to work, but that doesn't seem to play nice with blaze and it also messes up the other breadcrumbs that aren't anonymous functions.

**Comment by monbro** [comment]
You are right, as it is a function it needs to be executed. I haven't tried my suggestion but will test it when I got some time.

**Comment by Asparagirl** [comment]
Any news on this?

**Comment by 132041** [comment]
+1

**Comment by mazing** [comment]
+1

**Comment by mazing** [comment]
@JoshuaNovak919, what do you mean by calling `title()` instead of `title`? I really need a workaround :-)

**Comment by monbro** [comment]
In the new verson 1.0.8 which was released today, there is a full documentation on how to use a function for the title. Please have a look at the [advanced example](http://meteor-breadcrumb-plugin-advanced-example.meteor.com/function-title/some_parameter_here).
