### ISSUE TITLE
support categories tree use-case

### ISSUE THREAD

**Issue by ivankravchenko** [monbro/meteor-breadcrumb-plugin#3]
Say, I want to achieve result:
`Home > Some parent category > Child 1 > Child 1_1 > Product title`
(home link, categories path (multiple levels), product)
How is it can be done with monbro/meteor-breadcrumb-plugin?

**Comment by monbro** [comment]
Well at the moment one child can have one parent. But one parent can have multiple children. 
So for `Child 1` `Child 2` and `Child 3` you will simply define the same parent.

**Comment by monbro** [comment]
I assume this question is solved.
