### ISSUE TITLE
How to disable when no breadcrumb available

### ISSUE THREAD

**Issue by exocode** [monbro/meteor-breadcrumb-plugin#4]
I am quite new to Meteor and I don't found out how to disable the breadcrumbs with a `if, else` statement.

`Breadcrumb.length()` always returns 1, also when no title was given. 

What I have so far:

``` html
<template name="Breadcrumbs">
    {{#if breadcrumbExists}}
        <!-- START BREADCRUMB -->
        <ul class="breadcrumb">
            {{#each Breadcrumb}}
                <li class="">
                    <a href="#" class="{{cssClasses}}">{{title}}</a>
                </li>
            {{/each}}
        </ul>
    {{/if}}
    <!-- END BREADCRUMB -->
</template>
```

``` coffeescript
Template.Breadcrumbs.helpers
  breadcrumbExists: ->
    if Breadcrumb.getAll()[0].title == "This page has no title"
      false
    else
      true

```

What I am doing wrong? Or should this be done with a Session? Suggestions?

**Comment by monbro** [comment]
With Breadcrumb.getAll()[0] you are always checking if a title exists for the very parent Page (mostly it would be Home or Dashboard). Instead you need to check for the current page I assume? 

So you could try the following:

``` js
Template.Breadcrumbs.helpers
  breadcrumbExists: ->
    if Router.current().route.options.title == undefined
      false
    else
      true
```

**Comment by monbro** [comment]
I will add a function where you can easily disable the breadcrumb for a single route. Would that be easier for you then?

**Comment by monbro** [comment]
Please have a look on how to specify a [default title](https://github.com/monbro/meteor-breadcrumb-plugin/#1-example-iron-route-with-multiple-levels). If this is not solving your problem, please reopen the ticket.
