### ISSUE TITLE
when release date for new features?

### ISSUE THREAD

**Issue by thearabbit** [monbro/meteor-breadcrumb-plugin#6]
when release date for new features like:
- namespace: crumbTitle, ....
- disable on end of breadcrumb
- don't show if breadcrumb don't exist
  .....

Or have any solution by manual, I need it.

**Comment by monbro** [comment]
Please have a look at the latest release v1.0.10. Better namespacing should be implemented in version v2.0 - please don't ask for when, as this is a open source project :-) feel free to contribute :+1:

**Comment by thearabbit** [comment]
Thanks, but now I change to `Flow Router`.
